New commit

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -32,10 +32,10 @@ jobs:
       - name: Validate
         run: php gwm diag
 
-      - name: Deploy
+      - name: Update
         run: |
           git add ./resources
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
-          git commit -am "Automated commit"
+          git commit -am "Automated commit" || echo "ignore commit failure, proceed"
           git push
